apiVersion: v1
kind: Service
metadata:
  name: java-maven
spec:
  type: LoadBalancer
  selector:
    app: java-maven
  ports:
  - port: 8080
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-maven
spec:
  replicas: 2
  
  selector:
    matchLabels:
      app: java-maven
  template:
    metadata:
      labels:
        app: java-maven
    spec:
      containers:
      - name: java-maven
        image: riyadrb/maven
        resources:
          limits:
            memory: "128Mi"
            cpu: "225m"
        ports:
        - containerPort: 8080
